### ISSUE TITLE
check-requires: derivation-parser: error on token

### ISSUE THREAD

**Issue by lexi-lambda** [racket/macro-debugger#23]
The following file produces an error when running `check-requires` on it:

```racket
#lang racket/base

(module transformer racket/base
  (require (for-syntax racket/base
                       syntax/parse)
           racket/require
           racket/require-syntax)

  (provide req-transform)

  (define-require-syntax req-transform
    (λ (stx)
      (syntax-case stx ()
        [(_ require-spec)
         #'(filtered-in values require-spec)]))))

(require 'transformer
         (req-transform racket/base))
```
```
$ raco check-requires -b /tmp/repro.rkt
(file "/tmp/repro.rkt"):
ERROR in (file "/tmp/repro.rkt")
derivation-parser: error on token #1403: <local-value, #<syntax:/Users/alexis/gits/racket/racket/racket/collects/syntax/parse/private/lib.rkt:63:55 -string>>
  context...:
   /Users/alexis/gits/racket/racket/racket/share/pkgs/parser-tools-lib/parser-tools/yacc.rkt:347:16: parsing-loop
   /Users/alexis/gits/racket/racket/racket/collects/racket/private/promise.rkt:96:0: force/generic
   /Users/alexis/gits/racket/racket/racket/share/pkgs/macro-debugger-text-lib/macro-debugger/model/trace.rkt:40:0: trace/result
   /Users/alexis/gits/racket/racket/racket/share/pkgs/macro-debugger-text-lib/macro-debugger/analysis/private/util.rkt:61:31
   /Users/alexis/gits/racket/racket/racket/share/pkgs/macro-debugger-text-lib/macro-debugger/analysis/check-requires.rkt:120:0: check-requires31
   /Users/alexis/gits/racket/racket/racket/share/pkgs/macro-debugger-text-lib/macro-debugger/analysis/check-requires.rkt:288:3: for-loop
   ...cket/cmdline.rkt:179:51
   (submod /Users/alexis/gits/racket/racket/racket/share/pkgs/macro-debugger-text-lib/macro-debugger/analysis/check-requires.rkt main): [running body]
   /Users/alexis/gits/racket/racket/racket/collects/raco/raco.rkt: [running body]
   /Users/alexis/gits/racket/racket/racket/collects/raco/main.rkt: [running body]
```

This is a minimal example I could create to reproduce the issue, but many things are strange about it:

  1. The error doesn’t happen if the definitions in the `transformer` submodule are inlined into the parent module.
  2. It doesn’t happen if the require transformer does not expand to `filtered-in`.
  3. It doesn’t happen if `syntax/parse` is not required… even though `syntax/parse` is never actually used anywhere.

Seems like some strange corner case is getting triggered, but I certainly have no idea what it could be.

**Comment by gfbee** [comment]
Here's a similar, very minimal example producing that error:
```
#lang racket
(require (only-in racket/provide filtered-out))
(provide (filtered-out values (all-from-out racket)))
```

**Comment by gfbee** [comment]
Oh, it's not check-requires having the problem. 

The Macro Stepper reports: "Macro stepper error (derivation) [details]."
Those details are part of the larger error we're getting:
"Internal error: derivation-parser: error on token #246: <local-value, #<syntax:/Applications/Racket v6.12/collects/syntax/parse/private/lib.rkt:63:55 -string>>"

**Comment by gfbee** [comment]
The macro stepper doesn't like `(syntax-local-eval #'proc)` in the implementation of [`filtered-out`](https://github.com/racket/racket/blob/a2ab778ddbb86f4ff890f3a8391873a44fcef3d4/racket/collects/racket/provide.rkt#L24), since replacing it with just `values` prevents the error.

The error mentions the `local-value` token, and there's a [FIXME](https://github.com/racket/macro-debugger/blob/13ee731da98fbe14a0d486d614a5c46f26ccd933/macro-debugger-text-lib/macro-debugger/model/reductions.rkt#L502) for it that might be related. That's far beyond my understanding, so the limit of my investigation.

**Comment by rmculpepper** [comment]
I believe this issue is fixed with the expander rewrite for Racket 7. There are lots of points in the expander that may force the initialization of the compile-time environment (and syntax-parse adds another kind of laziness into the mix). Previously, the macro stepper had to be aware of those points and discard spurious events (and there was always one more place that I hadn't thought of); now the expansion "observer" is handled more precisely and doesn't get those events in the first place. That's my guess about why the error used to happen but doesn't any more.

I'm closing this, but please reopen it if you still see the problem with a recent pre-release version of Racket.
